# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc0fe3a41588ad351b9a883b1353a325588f38fbac9a6715721718c8aee132862875ed46e53aa75568b7eb53b775302950909b1487437657523f78a6fa04c2d6

test:
  secret_key_base: deb0cb4d3d8d5890a2ce4ede65f69a71226e736b6db3fcfff7d3abe10382018282758201772be31660988cde0f3b960863d959ff4a4e045a3deca0d6d9870632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
